#!/usr/bin/env python3

"""
Script used to run the webservice locally.
"""

from argparse import ArgumentParser
from os import getenv

from clickandobey.discord.bot.commands.command_loader import CommandLoader
from clickandobey.discord.bot.command_loader_bot import CommandLoaderBot
from clickandobey.discord.bot.logging.logger import create_logger


def __parse_args():
    parser = ArgumentParser()

    parser.add_argument("--debug", action="store_true", help="Run the application in debug mode.")

    return parser.parse_args()


def main():
    """
    Main method used to start the webservice.
    """
    args = __parse_args()
    logger = create_logger(args.debug)
    logger.info("Starting Command Loader Discord Bot...")
    command_loader = CommandLoader(logger)
    command_loader.load_python_commands(getenv("COMMANDS_PYTHON_DIRECTORY", "/commands"))
    command_loader.load_yaml_commands(getenv("COMMANDS_YAML_DIRECTORY", "/commands"))
    command_loader.log_usage()

    command_loader_bot = CommandLoaderBot(command_loader, logger)
    command_loader_bot.run(getenv("DISCORD_TOKEN"))
    logger.info("Finished Hello Bot...")


if __name__ == "__main__":
    main()
