#!/usr/bin/env python3

"""
Script used to run the webservice locally.
"""

from argparse import ArgumentParser

from clickandobey.discord.bot.hello_bot import HelloBot
from clickandobey.discord.bot.logging.logger import create_logger


def __parse_args():
    parser = ArgumentParser()

    parser.add_argument("--debug", action="store_true", help="Run the application in debug mode.")

    return parser.parse_args()


def main():
    """
    Main method used to start the webservice.
    """
    args = __parse_args()
    logger = create_logger(args.debug)
    logger.info("Starting Hello Bot...")
    HelloBot(logger)
    logger.info("Finished Hello Bot...")


if __name__ == "__main__":
    main()
